export const ApiPath = {
    SERVEREVENTS: "api/serverevents",
    // LOGIN: "api/auth/credentials",
    // RETAILER_INFO: "api/mobile/vendorsession",
    // REVENUE: "api/chart/revenue",
    // DASHBOARD: "api/chart/dashboard",
    // POPULARPRODUCTS: "api/chart/popularproducts",
    // PRODUCT: "api/products",
    // CATEGORIES_PRODUCT: "api/categories",
    // INVOICE: 'api/orders',
    // REVENUE_EXPENDITURE: "api/accountingtransaction",
    // ACCOUNT: "api/accounts",
    // ACCOUNTING_TRANSACTION_GROUPS: "api/accountingtransactiongroups",
    // INVOICE_DETAIL: "api/orders/detail",
    // HISTORY: "api/rooms/history",
    // ORDERSTOCK: "api/orderstock",
    // USERS: "api/users",
    // ORDERSTOCK_DETAIL: "api/orderstock/detail",
    // RETURNGOODS: "api/returntosuppliers",
    // RETURNGOODS_DETAIL: "api/returntosuppliers/detail",
    // INVENTORY: "api/inventorycount",
    // INVENTORY_DETAIL: "api/inventorycount/detail",
    // ENDOFDAY: "mobile/endOfDay",
    // LOGOUT: "api/auth/logout",
    // CUSTOMER:"api/partners",
    // DEBT_DETAIL:"api/partners/paybooks",
    // POINT:"api/pointuse",
    // GROUPS:"api/groups/treeview",
}